### ISSUE TITLE
Velocity inquiry

### ISSUE THREAD

**Issue by je-santos** [lettucecfd/lettuce#102]
Hi,

I was trying to benchmark the lettuce single-phase porous media model with my existing codes, and I found something curious, which might be caused by some dumb mistake on my end.

In the simulation results in [this notebook](https://github.com/je-santos/lettuce/blob/bug/examples/flow_through_tube.ipynb), in the last plot, you can see that the fluid velocity increases with distance from the inlet, theoretically which should be constant through the domain.

Let me know if you can spot the mistake.

Many thanks!!!!

**Comment by Olllom** [comment]
Without looking into it in detail: Could this be due to the LBM being a pseudo-compressible method? If this is the case you could mitigate the issue by doing one of the following
a) decreasing the Mach number
b) increasing resolution
c) decreasing delta_rho

Finally, are you sure the simulation is fully converged?

**Comment by je-santos** [comment]
Thanks for your answer. Changing a) and c) did changed the velocity profile. It still looks a little funky. I'll let you guys know if I'm able to find the right set of parameters.

**Comment by Olllom** [comment]
Yes. I think that a) and c) should be equivalent in physical units. If you are interested in mass flux through the medium it's probably more sensible to monitor the momentum 'lattice.j' = rho * u instead of velocity.

In the incompressible limit (Ma->0) of course j=u. But due to finite Ma (pseudo-compressible) effects this will never be exactly obeyed in practice.

Note also that a lot of people use a volumetric body force rather than an actual pressure gradient to drive the flow. This avoids the pseudo-compression to some degree but is only appropriate for channel flows. If you have obstacles / an irregular domain, the body force leads to non-physical artifacts that you don't have under control. In contrast, pseudo-compression can be effectively controlled through the Mach number.
