### ISSUE TITLE
Question about grid_fine_to_coarse function

### ISSUE THREAD

**Issue by houxianxu** [lettucecfd/lettuce#122]
First, thanks for this awesome Pytorch-based LBM library.

I am new to LBM and have a question about [`grid_fine_to_coarse`](https://github.com/lettucecfd/lettuce/blob/d899f748e3b890e7b40881bdc87a7fba8afeb182/lettuce/util.py#L100) function. I do not get the idea why we set the relaxation parameter as `2 * tau_coarse / tau_fine` as follow:
`f_coarse = f_eq + 2 * tau_coarse / tau_fine * f_neq`

Thanks

**Comment by McBs** [comment]
Hi,
thanks! We are happy when people have fun with the framework!
We've implemented this function for some prototyping according to Lagrava et al. 2012 (Advances in multi-domain lattice Boltzmann grid refinement). The conversion should be described in detail in this paper.
Bests
Mario

**Comment by Olllom** [comment]
Hi @houxianxu. In LBM, the equilibrium distribution does not depend on the relaxation time `tau`. However, the magnitude of the **nonequilibrium** contribution `(f_neq = f - f_eq)` scales with `tau`, which in turn depends on the resolution. That's why we need to rescale the `f_neq` when switching resolution. You will find the same kind of scaling in each grid refinement scheme in the LBM.

**Comment by houxianxu** [comment]
Thank you very much for your reply. I naively thought `f_coarse` was just a downsampled version of `f_fine`, just like we resize an image. I'm really glad to know the physics behind this operation.

All the best

**Comment by Olllom** [comment]
Cool. I'll close this then. Feel free to open a new issue if you have more questions.
